rootProject.name = "myScripts"

// where we declair our subprojects
//include("libraries:my-library")
include("libraries:cAPI")
include("scripts:my-script")
include("scripts:my-script2")
include("scripts:MotherLoadMine")
include("scripts:cSkiller")
include("scripts:cNMZ")
include("scripts:cCombat")
include("scripts:cTutorialIsland")
include("scripts:TemplateScript")
include("scripts:cVorkath")
include("scripts:cFarming")
include("scripts:cCrabs")
include("scripts:cBirdhouses")
include("scripts:cZulrah")
include("scripts:cOrbCharger")
include("scripts:cAutoClicker")
include("scripts:cRunecrafting")